kafka:
  brokers:
    - "localhost:9092"
  topic: "orders"
  groupID: "order-service"

database:
  url: "postgres://username:password@localhost:5432/dbname?sslmode=disable"

server:
  port: "8080"

cache:
  capacity: 50