services:
  orders_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
    networks:
      - app-net

  kafka:
    image: bitnami/kafka:4.0
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "9094:9094"
    networks:
      - app-net

  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      - POSTGRES_USER=orders_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=orders_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:

volumes:
  pgdata:
